config/routes.rb
Rails.application.routes.draw do

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  #
  root 'home#index'

  resources :users do
    resources :meta_fields
  end

  resources :roles do
    member do
      put :update_status
    end
  end

  resource :dynamic_css, controller: :dynamic_css
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/meta_field.rb
class MetaField < ApplicationRecord

  belongs_to :user
end

app/models/role.rb
class Role < ApplicationRecord
  enum status: [ :active, :inactive ]


  validates_presence_of :name
  validates_uniqueness_of :name

  has_and_belongs_to_many :users
end

app/models/user.rb
class User < ApplicationRecord

  validates_presence_of :first_name, :last_name, :email
  validates_uniqueness_of :email

  has_many :meta_fields, dependent: :destroy
  has_and_belongs_to_many :roles, -> { where(status: :active)}
  has_one_attached :image


  accepts_nested_attributes_for :meta_fields, reject_if: :all_blank


  def role_names
    roles.pluck(:name)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/dynamic_css_controller.rb
class DynamicCssController < ApplicationController

  def show
    @background_color = session[:background_color] || 'white'
  end

  def update
    session[:background_color] = params[:background_color]
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController


end

app/controllers/meta_fields_controller.rb
class MetaFieldsController < ApplicationController

  def new
    @user = User.find params[:user_id]
    @meta_field = @user.meta_fields.build
    @temp_id = Time.now.to_i
    render layout: false
  end
end

app/controllers/roles_controller.rb
class RolesController < ApplicationController
  def index
    @roles = Role.all

  end

  def new
    @role = Role.new
  end

  def create
    @role = Role.new(params[:role].permit(:name))
    @role.active!
    if @role.save
      flash['success'] = 'New role created'
      redirect_to roles_path
    else
      render :new
    end
  end

  def update_status
    @role = Role.find(params[:id])
    if params[:status].present?
      @role.active!
    else
      @role.inactive!
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    sort_by ||= params[:sort_by]

    @users = User.joins(:roles)
    if params[:role_id].present?
      @users = @users.where(roles: {id: params[:role_id]})
    end
    @users = @users.order(sort_by).paginate(:page => params[:page], per_page: 10)
    @active_roles = Role.active
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @roles = Role.active
    @user = User.new
  end

  # GET /users/1/edit
  def edit
    @roles = Role.active
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.includes(:roles).find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:first_name,
                                   :last_name,
                                   :email,
                                   :image, role_ids: [],
                                   meta_fields_attributes: [:id, :name, :value])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/meta_fields_helper.rb
module MetaFieldsHelper
end

app/helpers/roles_helper.rb
module RolesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/dynamic_css/show.css.erb
.dynamic_css {
  background-color: <%= @background_color %>;
}

app/views/home/index.html.erb
<div class="card">
  <div class="card-body">
    Home Page <br>
    <%= color_field_tag 'background_color', session[:background_color], class: 'dynamic-background-color', data: {
        remote: true,
        url: dynamic_css_path(),
        method: :put
    } %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Testapp01</title>
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <link rel="stylesheet" href="<%= dynamic_css_path(format: :css) %>" type="text/css" id="link-dynamic-css"/>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body class="dynamic_css">
<div class="container">
  <nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" href="#">Test App 01</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item active">
          <%= link_to 'Home', root_path, class: 'nav-link' %>
        </li>
        <li class="nav-item">
          <%= link_to 'Roles', roles_path, class: 'nav-link' %>

        </li>
        <li class="nav-item">
          <%= link_to 'Users', users_path, class: 'nav-link' %>
        </li>
      </ul>
    </div>
  </nav>
  <%= yield %>
</div>

</body>
</html>

app/views/meta_fields/new.html.erb
<%= fields_for "user[meta_fields_attributes][#{@temp_id}]", @meta_field do |mf| %>
  <div class="form-group">
    <div class="row">
      <div class="col-6">
        <%= mf.text_field :name, class: "form-control", placeholder: 'Name' %>
      </div>
      <div class="col-6">
        <%= mf.text_field :value, class: "form-control", placeholder: 'Value' %>
      </div>
    </div>
  </div>
<% end %>

app/views/roles/index.html.erb
<div class="row">
  <div class="col-12">
    <%= link_to 'Add Roles', new_role_path, class: 'btn btn-primary' %>
    <hr>
    <div id="list-of-roles">
      <h4>List of Roles</h4>
      <table class="table">
        <thead>
        <tr>
          <th scope="col">Role</th>
          <th scope="col">Status</th>
        </tr>
        </thead>
        <tbody>
        <% @roles.each do |role| %>
          <tr>
            <td>
              <%= role.name %>
            </td>
            <td>
              <%= check_box_tag 'status', role.status, role.active?, class: 'update_status', data: {
                  id: role.id,
                  remote: true,
                  url: update_status_role_path(role.id),
                  method: :put
              } %>
            </td>
          </tr>
        <% end %>

        </tbody>
      </table>
    </div>

  </div>
</div>

app/views/roles/new.html.erb
<%= form_for @role do |f|%>
  <div>
    <%= f.label :name %>
    <%= f.text_field :name  %>
  </div>
  <div>
    <%= f.submit  %>
  </div>
<% end %>

app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :first_name %>
    <%= form.text_field :first_name, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :last_name %>
    <%= form.text_field :last_name, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :email %>
    <%= form.email_field :email, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :roles %>
    <%= form.collection_select :role_ids, @roles, :id, :name, {},
                               {:multiple => true, class: "form-control"} %>

  </div>

  <div class="form-group">
    <%= form.label :image %>
    <%= form.file_field :image, class: "form-control-file", accept: 'image/png,image/gif,image/jpeg' %>
  </div>

  <div class="meta-fields">
    <%= form.fields_for :meta_fields do |mf| %>
      <div class="form-group">
        <div class="row">
          <div class="col-6">
            <%= mf.text_field :name, class: "form-control", placeholder: 'Name' %>
          </div>
          <div class="col-6">
            <%= mf.text_field :value, class: "form-control", placeholder: 'Value' %>
          </div>
        </div>
      </div>
    <% end %>

  </div>

  <% if user.persisted? %>
    <div class="form-group">
      <%= link_to "Add Meta Fields", new_user_meta_field_path(user.id), remote: true,
                  class: 'btn btn-primary btn-sm add-user-meta-fields' %>

    </div>
  <% end %>

  <%= form.submit 'Submit', class: 'btn btn-primary' %>

<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>
<hr>
<%= link_to 'Show', @user, class: 'btn' %> |
<%= link_to 'Back', users_path, class: 'btn' %>

app/views/users/index.html.erb
<%= link_to 'New User', new_user_path, class: 'btn btn-primary btn-sm' %>
<hr>
<%= form_tag users_path, method: :get, class: 'form-inline mb-2' do %>

  <%= select_tag 'role_id', options_for_select(@active_roles.collect {|u| [u.name, u.id]}, params[:role_id]),
                 {include_blank: 'All Roles', class: 'form-control mr-2', id: 'filter-roles'} %>
  <div class="input-group mr-2">
    <div class="input-group-prepend">
      <div class="input-group-text">Sort by</div>
    </div>
    <%= select_tag 'sort_by', options_for_select([:first_name, :last_name, :email], params[:sort_by]),
                   {class: 'form-control', id: 'sort-by'} %>
  </div>

  <%= submit_tag 'Search', class: 'btn btn-secondary' %>
<% end %>

<table class="table table-striped">
  <thead>
  <tr>
    <th>First name</th>
    <th>Last name</th>
    <th>Email</th>
    <th>Roles</th>
    <th colspan="3"></th>
  </tr>
  </thead>

  <tbody>
  <% @users.each do |user| %>
    <tr>
      <td><%= user.first_name %></td>
      <td><%= user.last_name %></td>
      <td><%= user.email %></td>
      <td><%= user.role_names.join(', ') %></td>
      <td><%= link_to 'Show', user %></td>
      <td><%= link_to 'Edit', edit_user_path(user) %></td>
      <td><%= link_to 'Destroy', user, method: :delete, data: {confirm: 'Are you sure?'} %></td>
    </tr>
  <% end %>
  </tbody>
</table>

<br>
<%= will_paginate @users, renderer: WillPaginate::ActionView::BootstrapLinkRenderer %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>
<hr>
<%= link_to 'Back', users_path, class: 'btn' %>

app/views/users/show.html.erb
<table class="table table-bordered">
  <tr>
    <td>
      <strong>First name:</strong>
    </td>
    <td>
      <%= @user.first_name %>
    </td>
  </tr>
  <tr>
    <td>
      <strong>Last name:</strong>
    </td>
    <td>
      <%= @user.last_name %>
    </td>
  </tr>
  <tr>
    <td>
      <strong>Email:</strong>
    </td>
    <td>
      <%= @user.email %>
    </td>
  </tr>
  <tr>
    <td>
      <strong>Roles:</strong>
    </td>
    <td>
      <% @user.role_names.each do |role_name| %>
        <span class="badge badge-secondary"><%= role_name %></span>
      <% end %>
    </td>
  </tr>
  <tr>
    <td colspan="2">
      <% if @user.image.attached? %>
        <%= image_tag @user.image, alt: @user.first_name, class: "img-thumbnail", size: '200x200' %>
      <% else %>
        <i>Image not found</i>
      <% end %>
    </td>
  </tr>
  <% @user.meta_fields.each do |mf| %>
  <tr>
    <td>
      <strong><%= mf.name %>:</strong>
    </td>
    <td>
      <%= mf.value %>
    </td>
  </tr>
  <% end %>
</table>

<hr>
<%= link_to 'Edit', edit_user_path(@user), class: 'btn' %> |
<%= link_to 'Back', users_path, class: 'btn' %>